Repository cloudbees-oss/zendesk-java-client, pull requests merged in 2021-11, with the labels that each got.

#415 Add type attribute to Comment model
  src/main/java/org/zendesk/client/v2/model/Comment.java
  src/main/java/org/zendesk/client/v2/model/CommentType.java
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
Labels: enhancement

#419 Few docs about ITs
  CONTRIBUTING.adoc
Labels: documentation

#418 Configure the DefaultAsyncHttpClient to follow redirects
  src/main/java/org/zendesk/client/v2/Zendesk.java
Labels: bug

#417 Allow to delete TicketForm
  src/main/java/org/zendesk/client/v2/Zendesk.java
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
Labels: enhancement

#416 Configure the polling interval/delay to be less aggressive in ITs
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
Labels: chore
