Repository cloudbees-oss/zendesk-java-client, pull requests merged in 2023-11, with the labels that each got.

#619 Support List Locales operation
  README.md
  src/main/java/org/zendesk/client/v2/Zendesk.java
  src/main/java/org/zendesk/client/v2/model/Locale.java
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
  src/test/java/org/zendesk/client/v2/model/LocaleTest.java
Labels: enhancement

#630 Add Ticket properties to support safe update
  src/main/java/org/zendesk/client/v2/model/Ticket.java
  src/test/java/org/zendesk/client/v2/model/TicketTest.java
Labels: enhancement

#614 Use cursor based pagination for endpoints that support it
  src/main/java/org/zendesk/client/v2/Zendesk.java
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
Labels: chore

#634 Revert changes to getTriggersWithParameters due to CBP bug in API
  src/main/java/org/zendesk/client/v2/Zendesk.java
  src/test/java/org/zendesk/client/v2/RealSmokeTest.java
Labels: bug, skip-changelog
